palette = "catppuccin_mocha"
## palette = "rosepine_main"

# TODO: find a better way to manage color schemes

[character]
# success_symbol = "[❯](green)"
# error_symbol = "[❯](red)"
# vicmd_symbol = "[❮](maroon)"

# ❰❱

# catppuccin
success_symbol = "[❱](green)"
error_symbol = "[❱](red)"
vicmd_symbol = "[❰](maroon)"

## # rosepine
## success_symbol = "[❱](green)"
## error_symbol = "[❱](red)"
## vicmd_symbol = "[❰](gold)"

[username]
style_user = 'rosewater bold'
style_root = 'red bold'
format = '[$user]($style) in '
disabled = false

[hostname]
disabled = true

[directory]
truncation_length = 4

# catppuccin
style = "bold lavender"

## # rosepine
## style = "bold rose"

[palettes.rosepine_main]
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_low = "#21202e"
highlight_med = "#403d52"
highlight_high = "#524f67"

[palettes.rosepine_moon]
base = "#232136"
surface = "#2a273f"
overlay = "#393552"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ea9a97"
pine = "#3e8fb0"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_low = "#2a283e"
highlight_med = "#44415a"
highlight_high = "#56526e"

[palettes.rosepine_dawn]
base = "#faf4ed"
surface = "#fffaf3"
overlay = "#f2e9e1"
muted = "#9893a5"
subtle = "#797593"
text = "#575279"
love = "#b4637a"
gold = "#ea9d34"
rose = "#d7827e"
pine = "#286983"
foam = "#56949f"
iris = "#907aa9"
highlight_low = "#f4ede8"
highlight_med = "#dfdad9"
highlight_high = "#cecacd"


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
