#!/bin/bash

tmux new-window -t ${1}
tmux send-keys -t ${1}:1 "nvim" Enter
tmux new-window -t ${1}
tmux send-keys -t ${1}:2 "ssh arch" Enter
tmux send-keys -t ${1}:2 "cd ~/${2}" Enter
tmux new-window -t ${1}
tmux send-keys -t ${1}:3 "w3m duckduckgo.com" Enter
