#!/bin/bash

tmux send-keys -t ${1}:0 "ssh arch" Enter "cd ~/${2}" Enter
tmux new-window -t ${1}
tmux send-keys -t ${1}:1 "nvim" Enter
tmux new-window -t ${1}
tmux send-keys -t ${1}:2 "w3m duckduckgo.com" Enter
tmux new-window -t ${1} "python && zsh"
