#!/bin/bash

tmux send-keys -t learnesp:0 "cd ~/projects/learnesp" Enter
tmux new-window -t learnesp
tmux send-keys -t learnesp:1 "cd ~/projects/learnesp" Enter "nvim" Enter
tmux new-window -t learnesp
tmux send-keys -t learnesp:2 "ssh arch" Enter
tmux send-keys -t learnesp:2 "cd ~/projects/learnesp" Enter
tmux new-window -t learnesp
tmux send-keys -t learnesp:3 "w3m duckduckgo.com" Enter
