#!/bin/bash

tmux split-window -t ${1}:0
tmux send-keys -t ${1}:0.1 "clear" Enter "python" Enter
tmux resize-pane -t ${1}:0.0 -Z

tmux new-window -t ${1}
tmux send-keys -t ${1}:1 "nvim" Enter " hf"

tmux new-window -t ${1}
tmux send-keys -t ${1}:2 "w3m duckduckgo.com" Enter

tmux switch-client -t ${1}:1
